### ISSUE TITLE
Type incompatible for VERSION property

### ISSUE THREAD

**Issue by windmemory** [Chatie/wechaty-puppet#30]
Recently I noticed that the typescript is complaining about the type incompatible for VERSION property. So I think it would be better to add a type to the VERSION property as a `string`.

```shell
Class static side 'typeof PuppetPadchat' incorrectly extends base class static side 'typeof Puppet'.
    Types of property 'VERSION' are incompatible.
        Type 'string' is not assignable to type '"0.0.0"'.
```

**Comment by zixia** [comment]
Thanks for the fix!

**Comment by zixia** [comment]
Ok. and you should include the version bumping in the PR next time!

**Comment by windmemory** [comment]
Ok, close this issue for now :)
